/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R01RootRouteRouteImport } from './routes/01-root-route'
import { Route as R02AnatomyOfARouteRouteImport } from './routes/02-anatomy-of-a-route'
import { Route as R03LinkRouteImport } from './routes/03-link'
import { Route as R04IndexRouteIndexRouteImport } from './routes/04-index-route/index'
import { Route as R04IndexRouteChildRouteImport } from './routes/04-index-route/child'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R01RootRouteRoute = R01RootRouteRouteImport.update({
  id: '/01-root-route',
  path: '/01-root-route',
  getParentRoute: () => rootRouteImport,
} as any)
const R02AnatomyOfARouteRoute = R02AnatomyOfARouteRouteImport.update({
  id: '/02-anatomy-of-a-route',
  path: '/02-anatomy-of-a-route',
  getParentRoute: () => rootRouteImport,
} as any)
const R03LinkRoute = R03LinkRouteImport.update({
  id: '/03-link',
  path: '/03-link',
  getParentRoute: () => rootRouteImport,
} as any)
const R04IndexRouteIndexRoute = R04IndexRouteIndexRouteImport.update({
  id: '/04-index-route/',
  path: '/04-index-route/',
  getParentRoute: () => rootRouteImport,
} as any)
const R04IndexRouteChildRoute = R04IndexRouteChildRouteImport.update({
  id: '/04-index-route/child',
  path: '/04-index-route/child',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/01-root-route': typeof R01RootRouteRoute
  '/02-anatomy-of-a-route': typeof R02AnatomyOfARouteRoute
  '/03-link': typeof R03LinkRoute
  '/04-index-route/child': typeof R04IndexRouteChildRoute
  '/04-index-route/': typeof R04IndexRouteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/01-root-route': typeof R01RootRouteRoute
  '/02-anatomy-of-a-route': typeof R02AnatomyOfARouteRoute
  '/03-link': typeof R03LinkRoute
  '/04-index-route/child': typeof R04IndexRouteChildRoute
  '/04-index-route': typeof R04IndexRouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/01-root-route': typeof R01RootRouteRoute
  '/02-anatomy-of-a-route': typeof R02AnatomyOfARouteRoute
  '/03-link': typeof R03LinkRoute
  '/04-index-route/child': typeof R04IndexRouteChildRoute
  '/04-index-route/': typeof R04IndexRouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/01-root-route'
    | '/02-anatomy-of-a-route'
    | '/03-link'
    | '/04-index-route/child'
    | '/04-index-route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/01-root-route'
    | '/02-anatomy-of-a-route'
    | '/03-link'
    | '/04-index-route/child'
    | '/04-index-route'
  id:
    | '__root__'
    | '/'
    | '/01-root-route'
    | '/02-anatomy-of-a-route'
    | '/03-link'
    | '/04-index-route/child'
    | '/04-index-route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R01RootRouteRoute: typeof R01RootRouteRoute
  R02AnatomyOfARouteRoute: typeof R02AnatomyOfARouteRoute
  R03LinkRoute: typeof R03LinkRoute
  R04IndexRouteChildRoute: typeof R04IndexRouteChildRoute
  R04IndexRouteIndexRoute: typeof R04IndexRouteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/01-root-route': {
      id: '/01-root-route'
      path: '/01-root-route'
      fullPath: '/01-root-route'
      preLoaderRoute: typeof R01RootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/02-anatomy-of-a-route': {
      id: '/02-anatomy-of-a-route'
      path: '/02-anatomy-of-a-route'
      fullPath: '/02-anatomy-of-a-route'
      preLoaderRoute: typeof R02AnatomyOfARouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/03-link': {
      id: '/03-link'
      path: '/03-link'
      fullPath: '/03-link'
      preLoaderRoute: typeof R03LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/04-index-route/': {
      id: '/04-index-route/'
      path: '/04-index-route'
      fullPath: '/04-index-route/'
      preLoaderRoute: typeof R04IndexRouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/04-index-route/child': {
      id: '/04-index-route/child'
      path: '/04-index-route/child'
      fullPath: '/04-index-route/child'
      preLoaderRoute: typeof R04IndexRouteChildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R01RootRouteRoute: R01RootRouteRoute,
  R02AnatomyOfARouteRoute: R02AnatomyOfARouteRoute,
  R03LinkRoute: R03LinkRoute,
  R04IndexRouteChildRoute: R04IndexRouteChildRoute,
  R04IndexRouteIndexRoute: R04IndexRouteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
