/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R01RootRouteRouteImport } from './routes/01-root-route'
import { Route as R02AnatomyOfARouteRouteImport } from './routes/02-anatomy-of-a-route'
import { Route as R03LinkRouteImport } from './routes/03-link'
import { Route as R15RelativeLinksRouteRouteImport } from './routes/15-relative-links/route'
import { Route as R04ColocationIndexRouteImport } from './routes/04-colocation/index'
import { Route as R05IndexRouteIndexRouteImport } from './routes/05-index-route/index'
import { Route as R05IndexRouteChildRouteImport } from './routes/05-index-route/child'
import { Route as R06DynamicSegmentProductIdRouteImport } from './routes/06-dynamic-segment/$productId'
import { Route as R07SplatSplatRouteImport } from './routes/07-splat/$'
import { Route as R08OptionalParamChar123CategoryChar125RouteImport } from './routes/08-optional-param/{-$category}'
import { Route as R09LayoutShopRouteImport } from './routes/09-layout/shop'
import { Route as R10NestedLayoutShopRouteRouteImport } from './routes/10-nested-layout/shop/route'
import { Route as R11PathlessLayoutLegalRouteImport } from './routes/11-pathless-layout/_legal'
import { Route as R11PathlessLayoutShopRouteImport } from './routes/11-pathless-layout/_shop'
import { Route as R12RouteGrouplegalRouteRouteImport } from './routes/12-route-group/(legal)/route'
import { Route as R12RouteGroupshopRouteRouteImport } from './routes/12-route-group/(shop)/route'
import { Route as R13NonNestedProductsRouteImport } from './routes/13-non-nested/products'
import { Route as R14LocationIndexRouteImport } from './routes/14-location/index'
import { Route as R14LocationCategoryRouteImport } from './routes/14-location/$category'
import { Route as R15RelativeLinksIndexRouteImport } from './routes/15-relative-links/index'
import { Route as R16RouteMatchingAboutRouteImport } from './routes/16-route-matching/about'
import { Route as R16RouteMatchingProductsRouteImport } from './routes/16-route-matching/products'
import { Route as R17EscapeCharactersSitemapDotxmlRouteImport } from './routes/17-escape-characters/sitemap[.]xml'
import { Route as R19LoaderProductsRouteImport } from './routes/19-loader/products'
import { Route as R20PendingComponentProductsRouteImport } from './routes/20-pending-component/products'
import { Route as R21SearchStringNoReplaceProductsRouteImport } from './routes/21-search-string-no-replace/products'
import { Route as R21UseNavigateCheckoutRouteImport } from './routes/21-use-navigate/checkout'
import { Route as R22SearchStringReplaceProductsRouteImport } from './routes/22-search-string-replace/products'
import { Route as R23SearchJsonProductsRouteImport } from './routes/23-search-json/products'
import { Route as R24SearchJsonZodProductsRouteImport } from './routes/24-search-json-zod/products'
import { Route as R09LayoutShopIndexRouteImport } from './routes/09-layout/shop.index'
import { Route as R09LayoutShopAboutRouteImport } from './routes/09-layout/shop.about'
import { Route as R09LayoutShopProductsRouteImport } from './routes/09-layout/shop.products'
import { Route as R10NestedLayoutShopIndexRouteImport } from './routes/10-nested-layout/shop/index'
import { Route as R10NestedLayoutShopAboutRouteImport } from './routes/10-nested-layout/shop/about'
import { Route as R10NestedLayoutShopProductsRouteImport } from './routes/10-nested-layout/shop/products'
import { Route as R11PathlessLayoutLegalPrivacyRouteImport } from './routes/11-pathless-layout/_legal.privacy'
import { Route as R11PathlessLayoutLegalTermsRouteImport } from './routes/11-pathless-layout/_legal.terms'
import { Route as R11PathlessLayoutShopCartRouteImport } from './routes/11-pathless-layout/_shop.cart'
import { Route as R11PathlessLayoutShopProductsRouteImport } from './routes/11-pathless-layout/_shop.products'
import { Route as R12RouteGrouplegalPrivacyRouteImport } from './routes/12-route-group/(legal)/privacy'
import { Route as R12RouteGrouplegalTermsRouteImport } from './routes/12-route-group/(legal)/terms'
import { Route as R12RouteGroupshopCartRouteImport } from './routes/12-route-group/(shop)/cart'
import { Route as R12RouteGroupshopProductsRouteImport } from './routes/12-route-group/(shop)/products'
import { Route as R13NonNestedProductsIndexRouteImport } from './routes/13-non-nested/products.index'
import { Route as R13NonNestedProductsProductIdRouteImport } from './routes/13-non-nested/products.$productId'
import { Route as R13NonNestedProductsSaleRouteImport } from './routes/13-non-nested/products.sale'
import { Route as R15RelativeLinksProductsIndexRouteImport } from './routes/15-relative-links/products/index'
import { Route as R15RelativeLinksProductsProductIdRouteRouteImport } from './routes/15-relative-links/products/$productId/route'
import { Route as R16RouteMatchingProductsIndexRouteImport } from './routes/16-route-matching/products.index'
import { Route as R16RouteMatchingProductsSplatRouteImport } from './routes/16-route-matching/products.$'
import { Route as R16RouteMatchingProductsProductIdRouteImport } from './routes/16-route-matching/products.$productId'
import { Route as R16RouteMatchingProductsSpecialOfferRouteImport } from './routes/16-route-matching/products.specialOffer'
import { Route as R17EscapeCharactersSitemapXmlRouteImport } from './routes/17-escape-characters/sitemap.xml'
import { Route as R18UrlRewritesProductsProductIdRouteImport } from './routes/18-url-rewrites/products.$productId'
import { Route as R21UseNavigateOrdersOrderIdRouteImport } from './routes/21-use-navigate/orders.$orderId'
import { Route as R13NonNestedProductsProductIdCheckoutRouteImport } from './routes/13-non-nested/products_.$productId.checkout'
import { Route as R15RelativeLinksProductsProductIdIndexRouteImport } from './routes/15-relative-links/products/$productId/index'
import { Route as R15RelativeLinksProductsProductIdReviewsRouteImport } from './routes/15-relative-links/products/$productId/reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R01RootRouteRoute = R01RootRouteRouteImport.update({
  id: '/01-root-route',
  path: '/01-root-route',
  getParentRoute: () => rootRouteImport,
} as any)
const R02AnatomyOfARouteRoute = R02AnatomyOfARouteRouteImport.update({
  id: '/02-anatomy-of-a-route',
  path: '/02-anatomy-of-a-route',
  getParentRoute: () => rootRouteImport,
} as any)
const R03LinkRoute = R03LinkRouteImport.update({
  id: '/03-link',
  path: '/03-link',
  getParentRoute: () => rootRouteImport,
} as any)
const R15RelativeLinksRouteRoute = R15RelativeLinksRouteRouteImport.update({
  id: '/15-relative-links',
  path: '/15-relative-links',
  getParentRoute: () => rootRouteImport,
} as any)
const R04ColocationIndexRoute = R04ColocationIndexRouteImport.update({
  id: '/04-colocation/',
  path: '/04-colocation/',
  getParentRoute: () => rootRouteImport,
} as any)
const R05IndexRouteIndexRoute = R05IndexRouteIndexRouteImport.update({
  id: '/05-index-route/',
  path: '/05-index-route/',
  getParentRoute: () => rootRouteImport,
} as any)
const R05IndexRouteChildRoute = R05IndexRouteChildRouteImport.update({
  id: '/05-index-route/child',
  path: '/05-index-route/child',
  getParentRoute: () => rootRouteImport,
} as any)
const R06DynamicSegmentProductIdRoute =
  R06DynamicSegmentProductIdRouteImport.update({
    id: '/06-dynamic-segment/$productId',
    path: '/06-dynamic-segment/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const R07SplatSplatRoute = R07SplatSplatRouteImport.update({
  id: '/07-splat/$',
  path: '/07-splat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R08OptionalParamChar123CategoryChar125Route =
  R08OptionalParamChar123CategoryChar125RouteImport.update({
    id: '/08-optional-param/{-$category}',
    path: '/08-optional-param/{-$category}',
    getParentRoute: () => rootRouteImport,
  } as any)
const R09LayoutShopRoute = R09LayoutShopRouteImport.update({
  id: '/09-layout/shop',
  path: '/09-layout/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const R10NestedLayoutShopRouteRoute =
  R10NestedLayoutShopRouteRouteImport.update({
    id: '/10-nested-layout/shop',
    path: '/10-nested-layout/shop',
    getParentRoute: () => rootRouteImport,
  } as any)
const R11PathlessLayoutLegalRoute = R11PathlessLayoutLegalRouteImport.update({
  id: '/11-pathless-layout/_legal',
  path: '/11-pathless-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const R11PathlessLayoutShopRoute = R11PathlessLayoutShopRouteImport.update({
  id: '/11-pathless-layout/_shop',
  path: '/11-pathless-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const R12RouteGrouplegalRouteRoute = R12RouteGrouplegalRouteRouteImport.update({
  id: '/12-route-group/(legal)',
  path: '/12-route-group',
  getParentRoute: () => rootRouteImport,
} as any)
const R12RouteGroupshopRouteRoute = R12RouteGroupshopRouteRouteImport.update({
  id: '/12-route-group/(shop)',
  path: '/12-route-group',
  getParentRoute: () => rootRouteImport,
} as any)
const R13NonNestedProductsRoute = R13NonNestedProductsRouteImport.update({
  id: '/13-non-nested/products',
  path: '/13-non-nested/products',
  getParentRoute: () => rootRouteImport,
} as any)
const R14LocationIndexRoute = R14LocationIndexRouteImport.update({
  id: '/14-location/',
  path: '/14-location/',
  getParentRoute: () => rootRouteImport,
} as any)
const R14LocationCategoryRoute = R14LocationCategoryRouteImport.update({
  id: '/14-location/$category',
  path: '/14-location/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const R15RelativeLinksIndexRoute = R15RelativeLinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R15RelativeLinksRouteRoute,
} as any)
const R16RouteMatchingAboutRoute = R16RouteMatchingAboutRouteImport.update({
  id: '/16-route-matching/about',
  path: '/16-route-matching/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R16RouteMatchingProductsRoute =
  R16RouteMatchingProductsRouteImport.update({
    id: '/16-route-matching/products',
    path: '/16-route-matching/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const R17EscapeCharactersSitemapDotxmlRoute =
  R17EscapeCharactersSitemapDotxmlRouteImport.update({
    id: '/17-escape-characters/sitemap.xml',
    path: '/17-escape-characters/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const R19LoaderProductsRoute = R19LoaderProductsRouteImport.update({
  id: '/19-loader/products',
  path: '/19-loader/products',
  getParentRoute: () => rootRouteImport,
} as any)
const R20PendingComponentProductsRoute =
  R20PendingComponentProductsRouteImport.update({
    id: '/20-pending-component/products',
    path: '/20-pending-component/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const R21SearchStringNoReplaceProductsRoute =
  R21SearchStringNoReplaceProductsRouteImport.update({
    id: '/21-search-string-no-replace/products',
    path: '/21-search-string-no-replace/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const R21UseNavigateCheckoutRoute = R21UseNavigateCheckoutRouteImport.update({
  id: '/21-use-navigate/checkout',
  path: '/21-use-navigate/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const R22SearchStringReplaceProductsRoute =
  R22SearchStringReplaceProductsRouteImport.update({
    id: '/22-search-string-replace/products',
    path: '/22-search-string-replace/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const R23SearchJsonProductsRoute = R23SearchJsonProductsRouteImport.update({
  id: '/23-search-json/products',
  path: '/23-search-json/products',
  getParentRoute: () => rootRouteImport,
} as any)
const R24SearchJsonZodProductsRoute =
  R24SearchJsonZodProductsRouteImport.update({
    id: '/24-search-json-zod/products',
    path: '/24-search-json-zod/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const R09LayoutShopIndexRoute = R09LayoutShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R09LayoutShopRoute,
} as any)
const R09LayoutShopAboutRoute = R09LayoutShopAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => R09LayoutShopRoute,
} as any)
const R09LayoutShopProductsRoute = R09LayoutShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => R09LayoutShopRoute,
} as any)
const R10NestedLayoutShopIndexRoute =
  R10NestedLayoutShopIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => R10NestedLayoutShopRouteRoute,
  } as any)
const R10NestedLayoutShopAboutRoute =
  R10NestedLayoutShopAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => R10NestedLayoutShopRouteRoute,
  } as any)
const R10NestedLayoutShopProductsRoute =
  R10NestedLayoutShopProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => R10NestedLayoutShopRouteRoute,
  } as any)
const R11PathlessLayoutLegalPrivacyRoute =
  R11PathlessLayoutLegalPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => R11PathlessLayoutLegalRoute,
  } as any)
const R11PathlessLayoutLegalTermsRoute =
  R11PathlessLayoutLegalTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => R11PathlessLayoutLegalRoute,
  } as any)
const R11PathlessLayoutShopCartRoute =
  R11PathlessLayoutShopCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => R11PathlessLayoutShopRoute,
  } as any)
const R11PathlessLayoutShopProductsRoute =
  R11PathlessLayoutShopProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => R11PathlessLayoutShopRoute,
  } as any)
const R12RouteGrouplegalPrivacyRoute =
  R12RouteGrouplegalPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => R12RouteGrouplegalRouteRoute,
  } as any)
const R12RouteGrouplegalTermsRoute = R12RouteGrouplegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => R12RouteGrouplegalRouteRoute,
} as any)
const R12RouteGroupshopCartRoute = R12RouteGroupshopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => R12RouteGroupshopRouteRoute,
} as any)
const R12RouteGroupshopProductsRoute =
  R12RouteGroupshopProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => R12RouteGroupshopRouteRoute,
  } as any)
const R13NonNestedProductsIndexRoute =
  R13NonNestedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => R13NonNestedProductsRoute,
  } as any)
const R13NonNestedProductsProductIdRoute =
  R13NonNestedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => R13NonNestedProductsRoute,
  } as any)
const R13NonNestedProductsSaleRoute =
  R13NonNestedProductsSaleRouteImport.update({
    id: '/sale',
    path: '/sale',
    getParentRoute: () => R13NonNestedProductsRoute,
  } as any)
const R15RelativeLinksProductsIndexRoute =
  R15RelativeLinksProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => R15RelativeLinksRouteRoute,
  } as any)
const R15RelativeLinksProductsProductIdRouteRoute =
  R15RelativeLinksProductsProductIdRouteRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => R15RelativeLinksRouteRoute,
  } as any)
const R16RouteMatchingProductsIndexRoute =
  R16RouteMatchingProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => R16RouteMatchingProductsRoute,
  } as any)
const R16RouteMatchingProductsSplatRoute =
  R16RouteMatchingProductsSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => R16RouteMatchingProductsRoute,
  } as any)
const R16RouteMatchingProductsProductIdRoute =
  R16RouteMatchingProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => R16RouteMatchingProductsRoute,
  } as any)
const R16RouteMatchingProductsSpecialOfferRoute =
  R16RouteMatchingProductsSpecialOfferRouteImport.update({
    id: '/specialOffer',
    path: '/specialOffer',
    getParentRoute: () => R16RouteMatchingProductsRoute,
  } as any)
const R17EscapeCharactersSitemapXmlRoute =
  R17EscapeCharactersSitemapXmlRouteImport.update({
    id: '/17-escape-characters/sitemap/xml',
    path: '/17-escape-characters/sitemap/xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const R18UrlRewritesProductsProductIdRoute =
  R18UrlRewritesProductsProductIdRouteImport.update({
    id: '/18-url-rewrites/products/$productId',
    path: '/18-url-rewrites/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const R21UseNavigateOrdersOrderIdRoute =
  R21UseNavigateOrdersOrderIdRouteImport.update({
    id: '/21-use-navigate/orders/$orderId',
    path: '/21-use-navigate/orders/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const R13NonNestedProductsProductIdCheckoutRoute =
  R13NonNestedProductsProductIdCheckoutRouteImport.update({
    id: '/13-non-nested/products_/$productId/checkout',
    path: '/13-non-nested/products/$productId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const R15RelativeLinksProductsProductIdIndexRoute =
  R15RelativeLinksProductsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => R15RelativeLinksProductsProductIdRouteRoute,
  } as any)
const R15RelativeLinksProductsProductIdReviewsRoute =
  R15RelativeLinksProductsProductIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => R15RelativeLinksProductsProductIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/15-relative-links': typeof R15RelativeLinksRouteRouteWithChildren
  '/01-root-route': typeof R01RootRouteRoute
  '/02-anatomy-of-a-route': typeof R02AnatomyOfARouteRoute
  '/03-link': typeof R03LinkRoute
  '/10-nested-layout/shop': typeof R10NestedLayoutShopRouteRouteWithChildren
  '/12-route-group': typeof R12RouteGroupshopRouteRouteWithChildren
  '/05-index-route/child': typeof R05IndexRouteChildRoute
  '/06-dynamic-segment/$productId': typeof R06DynamicSegmentProductIdRoute
  '/07-splat/$': typeof R07SplatSplatRoute
  '/08-optional-param/{-$category}': typeof R08OptionalParamChar123CategoryChar125Route
  '/09-layout/shop': typeof R09LayoutShopRouteWithChildren
  '/11-pathless-layout': typeof R11PathlessLayoutShopRouteWithChildren
  '/13-non-nested/products': typeof R13NonNestedProductsRouteWithChildren
  '/14-location/$category': typeof R14LocationCategoryRoute
  '/16-route-matching/about': typeof R16RouteMatchingAboutRoute
  '/16-route-matching/products': typeof R16RouteMatchingProductsRouteWithChildren
  '/17-escape-characters/sitemap.xml': typeof R17EscapeCharactersSitemapDotxmlRoute
  '/19-loader/products': typeof R19LoaderProductsRoute
  '/20-pending-component/products': typeof R20PendingComponentProductsRoute
  '/21-search-string-no-replace/products': typeof R21SearchStringNoReplaceProductsRoute
  '/21-use-navigate/checkout': typeof R21UseNavigateCheckoutRoute
  '/22-search-string-replace/products': typeof R22SearchStringReplaceProductsRoute
  '/23-search-json/products': typeof R23SearchJsonProductsRoute
  '/24-search-json-zod/products': typeof R24SearchJsonZodProductsRoute
  '/04-colocation/': typeof R04ColocationIndexRoute
  '/05-index-route/': typeof R05IndexRouteIndexRoute
  '/14-location/': typeof R14LocationIndexRoute
  '/15-relative-links/': typeof R15RelativeLinksIndexRoute
  '/15-relative-links/products/$productId': typeof R15RelativeLinksProductsProductIdRouteRouteWithChildren
  '/09-layout/shop/about': typeof R09LayoutShopAboutRoute
  '/09-layout/shop/products': typeof R09LayoutShopProductsRoute
  '/10-nested-layout/shop/about': typeof R10NestedLayoutShopAboutRoute
  '/10-nested-layout/shop/products': typeof R10NestedLayoutShopProductsRoute
  '/11-pathless-layout/privacy': typeof R11PathlessLayoutLegalPrivacyRoute
  '/11-pathless-layout/terms': typeof R11PathlessLayoutLegalTermsRoute
  '/11-pathless-layout/cart': typeof R11PathlessLayoutShopCartRoute
  '/11-pathless-layout/products': typeof R11PathlessLayoutShopProductsRoute
  '/12-route-group/privacy': typeof R12RouteGrouplegalPrivacyRoute
  '/12-route-group/terms': typeof R12RouteGrouplegalTermsRoute
  '/12-route-group/cart': typeof R12RouteGroupshopCartRoute
  '/12-route-group/products': typeof R12RouteGroupshopProductsRoute
  '/13-non-nested/products/$productId': typeof R13NonNestedProductsProductIdRoute
  '/13-non-nested/products/sale': typeof R13NonNestedProductsSaleRoute
  '/16-route-matching/products/$': typeof R16RouteMatchingProductsSplatRoute
  '/16-route-matching/products/$productId': typeof R16RouteMatchingProductsProductIdRoute
  '/16-route-matching/products/specialOffer': typeof R16RouteMatchingProductsSpecialOfferRoute
  '/17-escape-characters/sitemap/xml': typeof R17EscapeCharactersSitemapXmlRoute
  '/18-url-rewrites/products/$productId': typeof R18UrlRewritesProductsProductIdRoute
  '/21-use-navigate/orders/$orderId': typeof R21UseNavigateOrdersOrderIdRoute
  '/09-layout/shop/': typeof R09LayoutShopIndexRoute
  '/10-nested-layout/shop/': typeof R10NestedLayoutShopIndexRoute
  '/13-non-nested/products/': typeof R13NonNestedProductsIndexRoute
  '/15-relative-links/products/': typeof R15RelativeLinksProductsIndexRoute
  '/16-route-matching/products/': typeof R16RouteMatchingProductsIndexRoute
  '/13-non-nested/products/$productId/checkout': typeof R13NonNestedProductsProductIdCheckoutRoute
  '/15-relative-links/products/$productId/reviews': typeof R15RelativeLinksProductsProductIdReviewsRoute
  '/15-relative-links/products/$productId/': typeof R15RelativeLinksProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/01-root-route': typeof R01RootRouteRoute
  '/02-anatomy-of-a-route': typeof R02AnatomyOfARouteRoute
  '/03-link': typeof R03LinkRoute
  '/12-route-group': typeof R12RouteGroupshopRouteRouteWithChildren
  '/05-index-route/child': typeof R05IndexRouteChildRoute
  '/06-dynamic-segment/$productId': typeof R06DynamicSegmentProductIdRoute
  '/07-splat/$': typeof R07SplatSplatRoute
  '/08-optional-param/{-$category}': typeof R08OptionalParamChar123CategoryChar125Route
  '/11-pathless-layout': typeof R11PathlessLayoutShopRouteWithChildren
  '/14-location/$category': typeof R14LocationCategoryRoute
  '/16-route-matching/about': typeof R16RouteMatchingAboutRoute
  '/17-escape-characters/sitemap.xml': typeof R17EscapeCharactersSitemapDotxmlRoute
  '/19-loader/products': typeof R19LoaderProductsRoute
  '/20-pending-component/products': typeof R20PendingComponentProductsRoute
  '/21-search-string-no-replace/products': typeof R21SearchStringNoReplaceProductsRoute
  '/21-use-navigate/checkout': typeof R21UseNavigateCheckoutRoute
  '/22-search-string-replace/products': typeof R22SearchStringReplaceProductsRoute
  '/23-search-json/products': typeof R23SearchJsonProductsRoute
  '/24-search-json-zod/products': typeof R24SearchJsonZodProductsRoute
  '/04-colocation': typeof R04ColocationIndexRoute
  '/05-index-route': typeof R05IndexRouteIndexRoute
  '/14-location': typeof R14LocationIndexRoute
  '/15-relative-links': typeof R15RelativeLinksIndexRoute
  '/09-layout/shop/about': typeof R09LayoutShopAboutRoute
  '/09-layout/shop/products': typeof R09LayoutShopProductsRoute
  '/10-nested-layout/shop/about': typeof R10NestedLayoutShopAboutRoute
  '/10-nested-layout/shop/products': typeof R10NestedLayoutShopProductsRoute
  '/11-pathless-layout/privacy': typeof R11PathlessLayoutLegalPrivacyRoute
  '/11-pathless-layout/terms': typeof R11PathlessLayoutLegalTermsRoute
  '/11-pathless-layout/cart': typeof R11PathlessLayoutShopCartRoute
  '/11-pathless-layout/products': typeof R11PathlessLayoutShopProductsRoute
  '/12-route-group/privacy': typeof R12RouteGrouplegalPrivacyRoute
  '/12-route-group/terms': typeof R12RouteGrouplegalTermsRoute
  '/12-route-group/cart': typeof R12RouteGroupshopCartRoute
  '/12-route-group/products': typeof R12RouteGroupshopProductsRoute
  '/13-non-nested/products/$productId': typeof R13NonNestedProductsProductIdRoute
  '/13-non-nested/products/sale': typeof R13NonNestedProductsSaleRoute
  '/16-route-matching/products/$': typeof R16RouteMatchingProductsSplatRoute
  '/16-route-matching/products/$productId': typeof R16RouteMatchingProductsProductIdRoute
  '/16-route-matching/products/specialOffer': typeof R16RouteMatchingProductsSpecialOfferRoute
  '/17-escape-characters/sitemap/xml': typeof R17EscapeCharactersSitemapXmlRoute
  '/18-url-rewrites/products/$productId': typeof R18UrlRewritesProductsProductIdRoute
  '/21-use-navigate/orders/$orderId': typeof R21UseNavigateOrdersOrderIdRoute
  '/09-layout/shop': typeof R09LayoutShopIndexRoute
  '/10-nested-layout/shop': typeof R10NestedLayoutShopIndexRoute
  '/13-non-nested/products': typeof R13NonNestedProductsIndexRoute
  '/15-relative-links/products': typeof R15RelativeLinksProductsIndexRoute
  '/16-route-matching/products': typeof R16RouteMatchingProductsIndexRoute
  '/13-non-nested/products/$productId/checkout': typeof R13NonNestedProductsProductIdCheckoutRoute
  '/15-relative-links/products/$productId/reviews': typeof R15RelativeLinksProductsProductIdReviewsRoute
  '/15-relative-links/products/$productId': typeof R15RelativeLinksProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/15-relative-links': typeof R15RelativeLinksRouteRouteWithChildren
  '/01-root-route': typeof R01RootRouteRoute
  '/02-anatomy-of-a-route': typeof R02AnatomyOfARouteRoute
  '/03-link': typeof R03LinkRoute
  '/10-nested-layout/shop': typeof R10NestedLayoutShopRouteRouteWithChildren
  '/12-route-group/(legal)': typeof R12RouteGrouplegalRouteRouteWithChildren
  '/12-route-group/(shop)': typeof R12RouteGroupshopRouteRouteWithChildren
  '/05-index-route/child': typeof R05IndexRouteChildRoute
  '/06-dynamic-segment/$productId': typeof R06DynamicSegmentProductIdRoute
  '/07-splat/$': typeof R07SplatSplatRoute
  '/08-optional-param/{-$category}': typeof R08OptionalParamChar123CategoryChar125Route
  '/09-layout/shop': typeof R09LayoutShopRouteWithChildren
  '/11-pathless-layout/_legal': typeof R11PathlessLayoutLegalRouteWithChildren
  '/11-pathless-layout/_shop': typeof R11PathlessLayoutShopRouteWithChildren
  '/13-non-nested/products': typeof R13NonNestedProductsRouteWithChildren
  '/14-location/$category': typeof R14LocationCategoryRoute
  '/16-route-matching/about': typeof R16RouteMatchingAboutRoute
  '/16-route-matching/products': typeof R16RouteMatchingProductsRouteWithChildren
  '/17-escape-characters/sitemap.xml': typeof R17EscapeCharactersSitemapDotxmlRoute
  '/19-loader/products': typeof R19LoaderProductsRoute
  '/20-pending-component/products': typeof R20PendingComponentProductsRoute
  '/21-search-string-no-replace/products': typeof R21SearchStringNoReplaceProductsRoute
  '/21-use-navigate/checkout': typeof R21UseNavigateCheckoutRoute
  '/22-search-string-replace/products': typeof R22SearchStringReplaceProductsRoute
  '/23-search-json/products': typeof R23SearchJsonProductsRoute
  '/24-search-json-zod/products': typeof R24SearchJsonZodProductsRoute
  '/04-colocation/': typeof R04ColocationIndexRoute
  '/05-index-route/': typeof R05IndexRouteIndexRoute
  '/14-location/': typeof R14LocationIndexRoute
  '/15-relative-links/': typeof R15RelativeLinksIndexRoute
  '/15-relative-links/products/$productId': typeof R15RelativeLinksProductsProductIdRouteRouteWithChildren
  '/09-layout/shop/about': typeof R09LayoutShopAboutRoute
  '/09-layout/shop/products': typeof R09LayoutShopProductsRoute
  '/10-nested-layout/shop/about': typeof R10NestedLayoutShopAboutRoute
  '/10-nested-layout/shop/products': typeof R10NestedLayoutShopProductsRoute
  '/11-pathless-layout/_legal/privacy': typeof R11PathlessLayoutLegalPrivacyRoute
  '/11-pathless-layout/_legal/terms': typeof R11PathlessLayoutLegalTermsRoute
  '/11-pathless-layout/_shop/cart': typeof R11PathlessLayoutShopCartRoute
  '/11-pathless-layout/_shop/products': typeof R11PathlessLayoutShopProductsRoute
  '/12-route-group/(legal)/privacy': typeof R12RouteGrouplegalPrivacyRoute
  '/12-route-group/(legal)/terms': typeof R12RouteGrouplegalTermsRoute
  '/12-route-group/(shop)/cart': typeof R12RouteGroupshopCartRoute
  '/12-route-group/(shop)/products': typeof R12RouteGroupshopProductsRoute
  '/13-non-nested/products/$productId': typeof R13NonNestedProductsProductIdRoute
  '/13-non-nested/products/sale': typeof R13NonNestedProductsSaleRoute
  '/16-route-matching/products/$': typeof R16RouteMatchingProductsSplatRoute
  '/16-route-matching/products/$productId': typeof R16RouteMatchingProductsProductIdRoute
  '/16-route-matching/products/specialOffer': typeof R16RouteMatchingProductsSpecialOfferRoute
  '/17-escape-characters/sitemap/xml': typeof R17EscapeCharactersSitemapXmlRoute
  '/18-url-rewrites/products/$productId': typeof R18UrlRewritesProductsProductIdRoute
  '/21-use-navigate/orders/$orderId': typeof R21UseNavigateOrdersOrderIdRoute
  '/09-layout/shop/': typeof R09LayoutShopIndexRoute
  '/10-nested-layout/shop/': typeof R10NestedLayoutShopIndexRoute
  '/13-non-nested/products/': typeof R13NonNestedProductsIndexRoute
  '/15-relative-links/products/': typeof R15RelativeLinksProductsIndexRoute
  '/16-route-matching/products/': typeof R16RouteMatchingProductsIndexRoute
  '/13-non-nested/products_/$productId/checkout': typeof R13NonNestedProductsProductIdCheckoutRoute
  '/15-relative-links/products/$productId/reviews': typeof R15RelativeLinksProductsProductIdReviewsRoute
  '/15-relative-links/products/$productId/': typeof R15RelativeLinksProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/15-relative-links'
    | '/01-root-route'
    | '/02-anatomy-of-a-route'
    | '/03-link'
    | '/10-nested-layout/shop'
    | '/12-route-group'
    | '/05-index-route/child'
    | '/06-dynamic-segment/$productId'
    | '/07-splat/$'
    | '/08-optional-param/{-$category}'
    | '/09-layout/shop'
    | '/11-pathless-layout'
    | '/13-non-nested/products'
    | '/14-location/$category'
    | '/16-route-matching/about'
    | '/16-route-matching/products'
    | '/17-escape-characters/sitemap.xml'
    | '/19-loader/products'
    | '/20-pending-component/products'
    | '/21-search-string-no-replace/products'
    | '/21-use-navigate/checkout'
    | '/22-search-string-replace/products'
    | '/23-search-json/products'
    | '/24-search-json-zod/products'
    | '/04-colocation/'
    | '/05-index-route/'
    | '/14-location/'
    | '/15-relative-links/'
    | '/15-relative-links/products/$productId'
    | '/09-layout/shop/about'
    | '/09-layout/shop/products'
    | '/10-nested-layout/shop/about'
    | '/10-nested-layout/shop/products'
    | '/11-pathless-layout/privacy'
    | '/11-pathless-layout/terms'
    | '/11-pathless-layout/cart'
    | '/11-pathless-layout/products'
    | '/12-route-group/privacy'
    | '/12-route-group/terms'
    | '/12-route-group/cart'
    | '/12-route-group/products'
    | '/13-non-nested/products/$productId'
    | '/13-non-nested/products/sale'
    | '/16-route-matching/products/$'
    | '/16-route-matching/products/$productId'
    | '/16-route-matching/products/specialOffer'
    | '/17-escape-characters/sitemap/xml'
    | '/18-url-rewrites/products/$productId'
    | '/21-use-navigate/orders/$orderId'
    | '/09-layout/shop/'
    | '/10-nested-layout/shop/'
    | '/13-non-nested/products/'
    | '/15-relative-links/products/'
    | '/16-route-matching/products/'
    | '/13-non-nested/products/$productId/checkout'
    | '/15-relative-links/products/$productId/reviews'
    | '/15-relative-links/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/01-root-route'
    | '/02-anatomy-of-a-route'
    | '/03-link'
    | '/12-route-group'
    | '/05-index-route/child'
    | '/06-dynamic-segment/$productId'
    | '/07-splat/$'
    | '/08-optional-param/{-$category}'
    | '/11-pathless-layout'
    | '/14-location/$category'
    | '/16-route-matching/about'
    | '/17-escape-characters/sitemap.xml'
    | '/19-loader/products'
    | '/20-pending-component/products'
    | '/21-search-string-no-replace/products'
    | '/21-use-navigate/checkout'
    | '/22-search-string-replace/products'
    | '/23-search-json/products'
    | '/24-search-json-zod/products'
    | '/04-colocation'
    | '/05-index-route'
    | '/14-location'
    | '/15-relative-links'
    | '/09-layout/shop/about'
    | '/09-layout/shop/products'
    | '/10-nested-layout/shop/about'
    | '/10-nested-layout/shop/products'
    | '/11-pathless-layout/privacy'
    | '/11-pathless-layout/terms'
    | '/11-pathless-layout/cart'
    | '/11-pathless-layout/products'
    | '/12-route-group/privacy'
    | '/12-route-group/terms'
    | '/12-route-group/cart'
    | '/12-route-group/products'
    | '/13-non-nested/products/$productId'
    | '/13-non-nested/products/sale'
    | '/16-route-matching/products/$'
    | '/16-route-matching/products/$productId'
    | '/16-route-matching/products/specialOffer'
    | '/17-escape-characters/sitemap/xml'
    | '/18-url-rewrites/products/$productId'
    | '/21-use-navigate/orders/$orderId'
    | '/09-layout/shop'
    | '/10-nested-layout/shop'
    | '/13-non-nested/products'
    | '/15-relative-links/products'
    | '/16-route-matching/products'
    | '/13-non-nested/products/$productId/checkout'
    | '/15-relative-links/products/$productId/reviews'
    | '/15-relative-links/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/15-relative-links'
    | '/01-root-route'
    | '/02-anatomy-of-a-route'
    | '/03-link'
    | '/10-nested-layout/shop'
    | '/12-route-group/(legal)'
    | '/12-route-group/(shop)'
    | '/05-index-route/child'
    | '/06-dynamic-segment/$productId'
    | '/07-splat/$'
    | '/08-optional-param/{-$category}'
    | '/09-layout/shop'
    | '/11-pathless-layout/_legal'
    | '/11-pathless-layout/_shop'
    | '/13-non-nested/products'
    | '/14-location/$category'
    | '/16-route-matching/about'
    | '/16-route-matching/products'
    | '/17-escape-characters/sitemap.xml'
    | '/19-loader/products'
    | '/20-pending-component/products'
    | '/21-search-string-no-replace/products'
    | '/21-use-navigate/checkout'
    | '/22-search-string-replace/products'
    | '/23-search-json/products'
    | '/24-search-json-zod/products'
    | '/04-colocation/'
    | '/05-index-route/'
    | '/14-location/'
    | '/15-relative-links/'
    | '/15-relative-links/products/$productId'
    | '/09-layout/shop/about'
    | '/09-layout/shop/products'
    | '/10-nested-layout/shop/about'
    | '/10-nested-layout/shop/products'
    | '/11-pathless-layout/_legal/privacy'
    | '/11-pathless-layout/_legal/terms'
    | '/11-pathless-layout/_shop/cart'
    | '/11-pathless-layout/_shop/products'
    | '/12-route-group/(legal)/privacy'
    | '/12-route-group/(legal)/terms'
    | '/12-route-group/(shop)/cart'
    | '/12-route-group/(shop)/products'
    | '/13-non-nested/products/$productId'
    | '/13-non-nested/products/sale'
    | '/16-route-matching/products/$'
    | '/16-route-matching/products/$productId'
    | '/16-route-matching/products/specialOffer'
    | '/17-escape-characters/sitemap/xml'
    | '/18-url-rewrites/products/$productId'
    | '/21-use-navigate/orders/$orderId'
    | '/09-layout/shop/'
    | '/10-nested-layout/shop/'
    | '/13-non-nested/products/'
    | '/15-relative-links/products/'
    | '/16-route-matching/products/'
    | '/13-non-nested/products_/$productId/checkout'
    | '/15-relative-links/products/$productId/reviews'
    | '/15-relative-links/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R15RelativeLinksRouteRoute: typeof R15RelativeLinksRouteRouteWithChildren
  R01RootRouteRoute: typeof R01RootRouteRoute
  R02AnatomyOfARouteRoute: typeof R02AnatomyOfARouteRoute
  R03LinkRoute: typeof R03LinkRoute
  R10NestedLayoutShopRouteRoute: typeof R10NestedLayoutShopRouteRouteWithChildren
  R12RouteGrouplegalRouteRoute: typeof R12RouteGrouplegalRouteRouteWithChildren
  R12RouteGroupshopRouteRoute: typeof R12RouteGroupshopRouteRouteWithChildren
  R05IndexRouteChildRoute: typeof R05IndexRouteChildRoute
  R06DynamicSegmentProductIdRoute: typeof R06DynamicSegmentProductIdRoute
  R07SplatSplatRoute: typeof R07SplatSplatRoute
  R08OptionalParamChar123CategoryChar125Route: typeof R08OptionalParamChar123CategoryChar125Route
  R09LayoutShopRoute: typeof R09LayoutShopRouteWithChildren
  R11PathlessLayoutLegalRoute: typeof R11PathlessLayoutLegalRouteWithChildren
  R11PathlessLayoutShopRoute: typeof R11PathlessLayoutShopRouteWithChildren
  R13NonNestedProductsRoute: typeof R13NonNestedProductsRouteWithChildren
  R14LocationCategoryRoute: typeof R14LocationCategoryRoute
  R16RouteMatchingAboutRoute: typeof R16RouteMatchingAboutRoute
  R16RouteMatchingProductsRoute: typeof R16RouteMatchingProductsRouteWithChildren
  R17EscapeCharactersSitemapDotxmlRoute: typeof R17EscapeCharactersSitemapDotxmlRoute
  R19LoaderProductsRoute: typeof R19LoaderProductsRoute
  R20PendingComponentProductsRoute: typeof R20PendingComponentProductsRoute
  R21SearchStringNoReplaceProductsRoute: typeof R21SearchStringNoReplaceProductsRoute
  R21UseNavigateCheckoutRoute: typeof R21UseNavigateCheckoutRoute
  R22SearchStringReplaceProductsRoute: typeof R22SearchStringReplaceProductsRoute
  R23SearchJsonProductsRoute: typeof R23SearchJsonProductsRoute
  R24SearchJsonZodProductsRoute: typeof R24SearchJsonZodProductsRoute
  R04ColocationIndexRoute: typeof R04ColocationIndexRoute
  R05IndexRouteIndexRoute: typeof R05IndexRouteIndexRoute
  R14LocationIndexRoute: typeof R14LocationIndexRoute
  R17EscapeCharactersSitemapXmlRoute: typeof R17EscapeCharactersSitemapXmlRoute
  R18UrlRewritesProductsProductIdRoute: typeof R18UrlRewritesProductsProductIdRoute
  R21UseNavigateOrdersOrderIdRoute: typeof R21UseNavigateOrdersOrderIdRoute
  R13NonNestedProductsProductIdCheckoutRoute: typeof R13NonNestedProductsProductIdCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/01-root-route': {
      id: '/01-root-route'
      path: '/01-root-route'
      fullPath: '/01-root-route'
      preLoaderRoute: typeof R01RootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/02-anatomy-of-a-route': {
      id: '/02-anatomy-of-a-route'
      path: '/02-anatomy-of-a-route'
      fullPath: '/02-anatomy-of-a-route'
      preLoaderRoute: typeof R02AnatomyOfARouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/03-link': {
      id: '/03-link'
      path: '/03-link'
      fullPath: '/03-link'
      preLoaderRoute: typeof R03LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/15-relative-links': {
      id: '/15-relative-links'
      path: '/15-relative-links'
      fullPath: '/15-relative-links'
      preLoaderRoute: typeof R15RelativeLinksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/04-colocation/': {
      id: '/04-colocation/'
      path: '/04-colocation'
      fullPath: '/04-colocation/'
      preLoaderRoute: typeof R04ColocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/05-index-route/': {
      id: '/05-index-route/'
      path: '/05-index-route'
      fullPath: '/05-index-route/'
      preLoaderRoute: typeof R05IndexRouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/05-index-route/child': {
      id: '/05-index-route/child'
      path: '/05-index-route/child'
      fullPath: '/05-index-route/child'
      preLoaderRoute: typeof R05IndexRouteChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/06-dynamic-segment/$productId': {
      id: '/06-dynamic-segment/$productId'
      path: '/06-dynamic-segment/$productId'
      fullPath: '/06-dynamic-segment/$productId'
      preLoaderRoute: typeof R06DynamicSegmentProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/07-splat/$': {
      id: '/07-splat/$'
      path: '/07-splat/$'
      fullPath: '/07-splat/$'
      preLoaderRoute: typeof R07SplatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/08-optional-param/{-$category}': {
      id: '/08-optional-param/{-$category}'
      path: '/08-optional-param/{-$category}'
      fullPath: '/08-optional-param/{-$category}'
      preLoaderRoute: typeof R08OptionalParamChar123CategoryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/09-layout/shop': {
      id: '/09-layout/shop'
      path: '/09-layout/shop'
      fullPath: '/09-layout/shop'
      preLoaderRoute: typeof R09LayoutShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10-nested-layout/shop': {
      id: '/10-nested-layout/shop'
      path: '/10-nested-layout/shop'
      fullPath: '/10-nested-layout/shop'
      preLoaderRoute: typeof R10NestedLayoutShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/11-pathless-layout/_legal': {
      id: '/11-pathless-layout/_legal'
      path: '/11-pathless-layout'
      fullPath: '/11-pathless-layout'
      preLoaderRoute: typeof R11PathlessLayoutLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/11-pathless-layout/_shop': {
      id: '/11-pathless-layout/_shop'
      path: '/11-pathless-layout'
      fullPath: '/11-pathless-layout'
      preLoaderRoute: typeof R11PathlessLayoutShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/12-route-group/(legal)': {
      id: '/12-route-group/(legal)'
      path: '/12-route-group'
      fullPath: '/12-route-group'
      preLoaderRoute: typeof R12RouteGrouplegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/12-route-group/(shop)': {
      id: '/12-route-group/(shop)'
      path: '/12-route-group'
      fullPath: '/12-route-group'
      preLoaderRoute: typeof R12RouteGroupshopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13-non-nested/products': {
      id: '/13-non-nested/products'
      path: '/13-non-nested/products'
      fullPath: '/13-non-nested/products'
      preLoaderRoute: typeof R13NonNestedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/14-location/': {
      id: '/14-location/'
      path: '/14-location'
      fullPath: '/14-location/'
      preLoaderRoute: typeof R14LocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/14-location/$category': {
      id: '/14-location/$category'
      path: '/14-location/$category'
      fullPath: '/14-location/$category'
      preLoaderRoute: typeof R14LocationCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/15-relative-links/': {
      id: '/15-relative-links/'
      path: '/'
      fullPath: '/15-relative-links/'
      preLoaderRoute: typeof R15RelativeLinksIndexRouteImport
      parentRoute: typeof R15RelativeLinksRouteRoute
    }
    '/16-route-matching/about': {
      id: '/16-route-matching/about'
      path: '/16-route-matching/about'
      fullPath: '/16-route-matching/about'
      preLoaderRoute: typeof R16RouteMatchingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/16-route-matching/products': {
      id: '/16-route-matching/products'
      path: '/16-route-matching/products'
      fullPath: '/16-route-matching/products'
      preLoaderRoute: typeof R16RouteMatchingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/17-escape-characters/sitemap.xml': {
      id: '/17-escape-characters/sitemap.xml'
      path: '/17-escape-characters/sitemap.xml'
      fullPath: '/17-escape-characters/sitemap.xml'
      preLoaderRoute: typeof R17EscapeCharactersSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/19-loader/products': {
      id: '/19-loader/products'
      path: '/19-loader/products'
      fullPath: '/19-loader/products'
      preLoaderRoute: typeof R19LoaderProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/20-pending-component/products': {
      id: '/20-pending-component/products'
      path: '/20-pending-component/products'
      fullPath: '/20-pending-component/products'
      preLoaderRoute: typeof R20PendingComponentProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-search-string-no-replace/products': {
      id: '/21-search-string-no-replace/products'
      path: '/21-search-string-no-replace/products'
      fullPath: '/21-search-string-no-replace/products'
      preLoaderRoute: typeof R21SearchStringNoReplaceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-use-navigate/checkout': {
      id: '/21-use-navigate/checkout'
      path: '/21-use-navigate/checkout'
      fullPath: '/21-use-navigate/checkout'
      preLoaderRoute: typeof R21UseNavigateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/22-search-string-replace/products': {
      id: '/22-search-string-replace/products'
      path: '/22-search-string-replace/products'
      fullPath: '/22-search-string-replace/products'
      preLoaderRoute: typeof R22SearchStringReplaceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/23-search-json/products': {
      id: '/23-search-json/products'
      path: '/23-search-json/products'
      fullPath: '/23-search-json/products'
      preLoaderRoute: typeof R23SearchJsonProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/24-search-json-zod/products': {
      id: '/24-search-json-zod/products'
      path: '/24-search-json-zod/products'
      fullPath: '/24-search-json-zod/products'
      preLoaderRoute: typeof R24SearchJsonZodProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/09-layout/shop/': {
      id: '/09-layout/shop/'
      path: '/'
      fullPath: '/09-layout/shop/'
      preLoaderRoute: typeof R09LayoutShopIndexRouteImport
      parentRoute: typeof R09LayoutShopRoute
    }
    '/09-layout/shop/about': {
      id: '/09-layout/shop/about'
      path: '/about'
      fullPath: '/09-layout/shop/about'
      preLoaderRoute: typeof R09LayoutShopAboutRouteImport
      parentRoute: typeof R09LayoutShopRoute
    }
    '/09-layout/shop/products': {
      id: '/09-layout/shop/products'
      path: '/products'
      fullPath: '/09-layout/shop/products'
      preLoaderRoute: typeof R09LayoutShopProductsRouteImport
      parentRoute: typeof R09LayoutShopRoute
    }
    '/10-nested-layout/shop/': {
      id: '/10-nested-layout/shop/'
      path: '/'
      fullPath: '/10-nested-layout/shop/'
      preLoaderRoute: typeof R10NestedLayoutShopIndexRouteImport
      parentRoute: typeof R10NestedLayoutShopRouteRoute
    }
    '/10-nested-layout/shop/about': {
      id: '/10-nested-layout/shop/about'
      path: '/about'
      fullPath: '/10-nested-layout/shop/about'
      preLoaderRoute: typeof R10NestedLayoutShopAboutRouteImport
      parentRoute: typeof R10NestedLayoutShopRouteRoute
    }
    '/10-nested-layout/shop/products': {
      id: '/10-nested-layout/shop/products'
      path: '/products'
      fullPath: '/10-nested-layout/shop/products'
      preLoaderRoute: typeof R10NestedLayoutShopProductsRouteImport
      parentRoute: typeof R10NestedLayoutShopRouteRoute
    }
    '/11-pathless-layout/_legal/privacy': {
      id: '/11-pathless-layout/_legal/privacy'
      path: '/privacy'
      fullPath: '/11-pathless-layout/privacy'
      preLoaderRoute: typeof R11PathlessLayoutLegalPrivacyRouteImport
      parentRoute: typeof R11PathlessLayoutLegalRoute
    }
    '/11-pathless-layout/_legal/terms': {
      id: '/11-pathless-layout/_legal/terms'
      path: '/terms'
      fullPath: '/11-pathless-layout/terms'
      preLoaderRoute: typeof R11PathlessLayoutLegalTermsRouteImport
      parentRoute: typeof R11PathlessLayoutLegalRoute
    }
    '/11-pathless-layout/_shop/cart': {
      id: '/11-pathless-layout/_shop/cart'
      path: '/cart'
      fullPath: '/11-pathless-layout/cart'
      preLoaderRoute: typeof R11PathlessLayoutShopCartRouteImport
      parentRoute: typeof R11PathlessLayoutShopRoute
    }
    '/11-pathless-layout/_shop/products': {
      id: '/11-pathless-layout/_shop/products'
      path: '/products'
      fullPath: '/11-pathless-layout/products'
      preLoaderRoute: typeof R11PathlessLayoutShopProductsRouteImport
      parentRoute: typeof R11PathlessLayoutShopRoute
    }
    '/12-route-group/(legal)/privacy': {
      id: '/12-route-group/(legal)/privacy'
      path: '/privacy'
      fullPath: '/12-route-group/privacy'
      preLoaderRoute: typeof R12RouteGrouplegalPrivacyRouteImport
      parentRoute: typeof R12RouteGrouplegalRouteRoute
    }
    '/12-route-group/(legal)/terms': {
      id: '/12-route-group/(legal)/terms'
      path: '/terms'
      fullPath: '/12-route-group/terms'
      preLoaderRoute: typeof R12RouteGrouplegalTermsRouteImport
      parentRoute: typeof R12RouteGrouplegalRouteRoute
    }
    '/12-route-group/(shop)/cart': {
      id: '/12-route-group/(shop)/cart'
      path: '/cart'
      fullPath: '/12-route-group/cart'
      preLoaderRoute: typeof R12RouteGroupshopCartRouteImport
      parentRoute: typeof R12RouteGroupshopRouteRoute
    }
    '/12-route-group/(shop)/products': {
      id: '/12-route-group/(shop)/products'
      path: '/products'
      fullPath: '/12-route-group/products'
      preLoaderRoute: typeof R12RouteGroupshopProductsRouteImport
      parentRoute: typeof R12RouteGroupshopRouteRoute
    }
    '/13-non-nested/products/': {
      id: '/13-non-nested/products/'
      path: '/'
      fullPath: '/13-non-nested/products/'
      preLoaderRoute: typeof R13NonNestedProductsIndexRouteImport
      parentRoute: typeof R13NonNestedProductsRoute
    }
    '/13-non-nested/products/$productId': {
      id: '/13-non-nested/products/$productId'
      path: '/$productId'
      fullPath: '/13-non-nested/products/$productId'
      preLoaderRoute: typeof R13NonNestedProductsProductIdRouteImport
      parentRoute: typeof R13NonNestedProductsRoute
    }
    '/13-non-nested/products/sale': {
      id: '/13-non-nested/products/sale'
      path: '/sale'
      fullPath: '/13-non-nested/products/sale'
      preLoaderRoute: typeof R13NonNestedProductsSaleRouteImport
      parentRoute: typeof R13NonNestedProductsRoute
    }
    '/15-relative-links/products/': {
      id: '/15-relative-links/products/'
      path: '/products'
      fullPath: '/15-relative-links/products/'
      preLoaderRoute: typeof R15RelativeLinksProductsIndexRouteImport
      parentRoute: typeof R15RelativeLinksRouteRoute
    }
    '/15-relative-links/products/$productId': {
      id: '/15-relative-links/products/$productId'
      path: '/products/$productId'
      fullPath: '/15-relative-links/products/$productId'
      preLoaderRoute: typeof R15RelativeLinksProductsProductIdRouteRouteImport
      parentRoute: typeof R15RelativeLinksRouteRoute
    }
    '/16-route-matching/products/': {
      id: '/16-route-matching/products/'
      path: '/'
      fullPath: '/16-route-matching/products/'
      preLoaderRoute: typeof R16RouteMatchingProductsIndexRouteImport
      parentRoute: typeof R16RouteMatchingProductsRoute
    }
    '/16-route-matching/products/$': {
      id: '/16-route-matching/products/$'
      path: '/$'
      fullPath: '/16-route-matching/products/$'
      preLoaderRoute: typeof R16RouteMatchingProductsSplatRouteImport
      parentRoute: typeof R16RouteMatchingProductsRoute
    }
    '/16-route-matching/products/$productId': {
      id: '/16-route-matching/products/$productId'
      path: '/$productId'
      fullPath: '/16-route-matching/products/$productId'
      preLoaderRoute: typeof R16RouteMatchingProductsProductIdRouteImport
      parentRoute: typeof R16RouteMatchingProductsRoute
    }
    '/16-route-matching/products/specialOffer': {
      id: '/16-route-matching/products/specialOffer'
      path: '/specialOffer'
      fullPath: '/16-route-matching/products/specialOffer'
      preLoaderRoute: typeof R16RouteMatchingProductsSpecialOfferRouteImport
      parentRoute: typeof R16RouteMatchingProductsRoute
    }
    '/17-escape-characters/sitemap/xml': {
      id: '/17-escape-characters/sitemap/xml'
      path: '/17-escape-characters/sitemap/xml'
      fullPath: '/17-escape-characters/sitemap/xml'
      preLoaderRoute: typeof R17EscapeCharactersSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/18-url-rewrites/products/$productId': {
      id: '/18-url-rewrites/products/$productId'
      path: '/18-url-rewrites/products/$productId'
      fullPath: '/18-url-rewrites/products/$productId'
      preLoaderRoute: typeof R18UrlRewritesProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/21-use-navigate/orders/$orderId': {
      id: '/21-use-navigate/orders/$orderId'
      path: '/21-use-navigate/orders/$orderId'
      fullPath: '/21-use-navigate/orders/$orderId'
      preLoaderRoute: typeof R21UseNavigateOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13-non-nested/products_/$productId/checkout': {
      id: '/13-non-nested/products_/$productId/checkout'
      path: '/13-non-nested/products/$productId/checkout'
      fullPath: '/13-non-nested/products/$productId/checkout'
      preLoaderRoute: typeof R13NonNestedProductsProductIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/15-relative-links/products/$productId/': {
      id: '/15-relative-links/products/$productId/'
      path: '/'
      fullPath: '/15-relative-links/products/$productId/'
      preLoaderRoute: typeof R15RelativeLinksProductsProductIdIndexRouteImport
      parentRoute: typeof R15RelativeLinksProductsProductIdRouteRoute
    }
    '/15-relative-links/products/$productId/reviews': {
      id: '/15-relative-links/products/$productId/reviews'
      path: '/reviews'
      fullPath: '/15-relative-links/products/$productId/reviews'
      preLoaderRoute: typeof R15RelativeLinksProductsProductIdReviewsRouteImport
      parentRoute: typeof R15RelativeLinksProductsProductIdRouteRoute
    }
  }
}

interface R15RelativeLinksProductsProductIdRouteRouteChildren {
  R15RelativeLinksProductsProductIdReviewsRoute: typeof R15RelativeLinksProductsProductIdReviewsRoute
  R15RelativeLinksProductsProductIdIndexRoute: typeof R15RelativeLinksProductsProductIdIndexRoute
}

const R15RelativeLinksProductsProductIdRouteRouteChildren: R15RelativeLinksProductsProductIdRouteRouteChildren =
  {
    R15RelativeLinksProductsProductIdReviewsRoute:
      R15RelativeLinksProductsProductIdReviewsRoute,
    R15RelativeLinksProductsProductIdIndexRoute:
      R15RelativeLinksProductsProductIdIndexRoute,
  }

const R15RelativeLinksProductsProductIdRouteRouteWithChildren =
  R15RelativeLinksProductsProductIdRouteRoute._addFileChildren(
    R15RelativeLinksProductsProductIdRouteRouteChildren,
  )

interface R15RelativeLinksRouteRouteChildren {
  R15RelativeLinksIndexRoute: typeof R15RelativeLinksIndexRoute
  R15RelativeLinksProductsProductIdRouteRoute: typeof R15RelativeLinksProductsProductIdRouteRouteWithChildren
  R15RelativeLinksProductsIndexRoute: typeof R15RelativeLinksProductsIndexRoute
}

const R15RelativeLinksRouteRouteChildren: R15RelativeLinksRouteRouteChildren = {
  R15RelativeLinksIndexRoute: R15RelativeLinksIndexRoute,
  R15RelativeLinksProductsProductIdRouteRoute:
    R15RelativeLinksProductsProductIdRouteRouteWithChildren,
  R15RelativeLinksProductsIndexRoute: R15RelativeLinksProductsIndexRoute,
}

const R15RelativeLinksRouteRouteWithChildren =
  R15RelativeLinksRouteRoute._addFileChildren(
    R15RelativeLinksRouteRouteChildren,
  )

interface R10NestedLayoutShopRouteRouteChildren {
  R10NestedLayoutShopAboutRoute: typeof R10NestedLayoutShopAboutRoute
  R10NestedLayoutShopProductsRoute: typeof R10NestedLayoutShopProductsRoute
  R10NestedLayoutShopIndexRoute: typeof R10NestedLayoutShopIndexRoute
}

const R10NestedLayoutShopRouteRouteChildren: R10NestedLayoutShopRouteRouteChildren =
  {
    R10NestedLayoutShopAboutRoute: R10NestedLayoutShopAboutRoute,
    R10NestedLayoutShopProductsRoute: R10NestedLayoutShopProductsRoute,
    R10NestedLayoutShopIndexRoute: R10NestedLayoutShopIndexRoute,
  }

const R10NestedLayoutShopRouteRouteWithChildren =
  R10NestedLayoutShopRouteRoute._addFileChildren(
    R10NestedLayoutShopRouteRouteChildren,
  )

interface R12RouteGrouplegalRouteRouteChildren {
  R12RouteGrouplegalPrivacyRoute: typeof R12RouteGrouplegalPrivacyRoute
  R12RouteGrouplegalTermsRoute: typeof R12RouteGrouplegalTermsRoute
}

const R12RouteGrouplegalRouteRouteChildren: R12RouteGrouplegalRouteRouteChildren =
  {
    R12RouteGrouplegalPrivacyRoute: R12RouteGrouplegalPrivacyRoute,
    R12RouteGrouplegalTermsRoute: R12RouteGrouplegalTermsRoute,
  }

const R12RouteGrouplegalRouteRouteWithChildren =
  R12RouteGrouplegalRouteRoute._addFileChildren(
    R12RouteGrouplegalRouteRouteChildren,
  )

interface R12RouteGroupshopRouteRouteChildren {
  R12RouteGroupshopCartRoute: typeof R12RouteGroupshopCartRoute
  R12RouteGroupshopProductsRoute: typeof R12RouteGroupshopProductsRoute
}

const R12RouteGroupshopRouteRouteChildren: R12RouteGroupshopRouteRouteChildren =
  {
    R12RouteGroupshopCartRoute: R12RouteGroupshopCartRoute,
    R12RouteGroupshopProductsRoute: R12RouteGroupshopProductsRoute,
  }

const R12RouteGroupshopRouteRouteWithChildren =
  R12RouteGroupshopRouteRoute._addFileChildren(
    R12RouteGroupshopRouteRouteChildren,
  )

interface R09LayoutShopRouteChildren {
  R09LayoutShopAboutRoute: typeof R09LayoutShopAboutRoute
  R09LayoutShopProductsRoute: typeof R09LayoutShopProductsRoute
  R09LayoutShopIndexRoute: typeof R09LayoutShopIndexRoute
}

const R09LayoutShopRouteChildren: R09LayoutShopRouteChildren = {
  R09LayoutShopAboutRoute: R09LayoutShopAboutRoute,
  R09LayoutShopProductsRoute: R09LayoutShopProductsRoute,
  R09LayoutShopIndexRoute: R09LayoutShopIndexRoute,
}

const R09LayoutShopRouteWithChildren = R09LayoutShopRoute._addFileChildren(
  R09LayoutShopRouteChildren,
)

interface R11PathlessLayoutLegalRouteChildren {
  R11PathlessLayoutLegalPrivacyRoute: typeof R11PathlessLayoutLegalPrivacyRoute
  R11PathlessLayoutLegalTermsRoute: typeof R11PathlessLayoutLegalTermsRoute
}

const R11PathlessLayoutLegalRouteChildren: R11PathlessLayoutLegalRouteChildren =
  {
    R11PathlessLayoutLegalPrivacyRoute: R11PathlessLayoutLegalPrivacyRoute,
    R11PathlessLayoutLegalTermsRoute: R11PathlessLayoutLegalTermsRoute,
  }

const R11PathlessLayoutLegalRouteWithChildren =
  R11PathlessLayoutLegalRoute._addFileChildren(
    R11PathlessLayoutLegalRouteChildren,
  )

interface R11PathlessLayoutShopRouteChildren {
  R11PathlessLayoutShopCartRoute: typeof R11PathlessLayoutShopCartRoute
  R11PathlessLayoutShopProductsRoute: typeof R11PathlessLayoutShopProductsRoute
}

const R11PathlessLayoutShopRouteChildren: R11PathlessLayoutShopRouteChildren = {
  R11PathlessLayoutShopCartRoute: R11PathlessLayoutShopCartRoute,
  R11PathlessLayoutShopProductsRoute: R11PathlessLayoutShopProductsRoute,
}

const R11PathlessLayoutShopRouteWithChildren =
  R11PathlessLayoutShopRoute._addFileChildren(
    R11PathlessLayoutShopRouteChildren,
  )

interface R13NonNestedProductsRouteChildren {
  R13NonNestedProductsProductIdRoute: typeof R13NonNestedProductsProductIdRoute
  R13NonNestedProductsSaleRoute: typeof R13NonNestedProductsSaleRoute
  R13NonNestedProductsIndexRoute: typeof R13NonNestedProductsIndexRoute
}

const R13NonNestedProductsRouteChildren: R13NonNestedProductsRouteChildren = {
  R13NonNestedProductsProductIdRoute: R13NonNestedProductsProductIdRoute,
  R13NonNestedProductsSaleRoute: R13NonNestedProductsSaleRoute,
  R13NonNestedProductsIndexRoute: R13NonNestedProductsIndexRoute,
}

const R13NonNestedProductsRouteWithChildren =
  R13NonNestedProductsRoute._addFileChildren(R13NonNestedProductsRouteChildren)

interface R16RouteMatchingProductsRouteChildren {
  R16RouteMatchingProductsSplatRoute: typeof R16RouteMatchingProductsSplatRoute
  R16RouteMatchingProductsProductIdRoute: typeof R16RouteMatchingProductsProductIdRoute
  R16RouteMatchingProductsSpecialOfferRoute: typeof R16RouteMatchingProductsSpecialOfferRoute
  R16RouteMatchingProductsIndexRoute: typeof R16RouteMatchingProductsIndexRoute
}

const R16RouteMatchingProductsRouteChildren: R16RouteMatchingProductsRouteChildren =
  {
    R16RouteMatchingProductsSplatRoute: R16RouteMatchingProductsSplatRoute,
    R16RouteMatchingProductsProductIdRoute:
      R16RouteMatchingProductsProductIdRoute,
    R16RouteMatchingProductsSpecialOfferRoute:
      R16RouteMatchingProductsSpecialOfferRoute,
    R16RouteMatchingProductsIndexRoute: R16RouteMatchingProductsIndexRoute,
  }

const R16RouteMatchingProductsRouteWithChildren =
  R16RouteMatchingProductsRoute._addFileChildren(
    R16RouteMatchingProductsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R15RelativeLinksRouteRoute: R15RelativeLinksRouteRouteWithChildren,
  R01RootRouteRoute: R01RootRouteRoute,
  R02AnatomyOfARouteRoute: R02AnatomyOfARouteRoute,
  R03LinkRoute: R03LinkRoute,
  R10NestedLayoutShopRouteRoute: R10NestedLayoutShopRouteRouteWithChildren,
  R12RouteGrouplegalRouteRoute: R12RouteGrouplegalRouteRouteWithChildren,
  R12RouteGroupshopRouteRoute: R12RouteGroupshopRouteRouteWithChildren,
  R05IndexRouteChildRoute: R05IndexRouteChildRoute,
  R06DynamicSegmentProductIdRoute: R06DynamicSegmentProductIdRoute,
  R07SplatSplatRoute: R07SplatSplatRoute,
  R08OptionalParamChar123CategoryChar125Route:
    R08OptionalParamChar123CategoryChar125Route,
  R09LayoutShopRoute: R09LayoutShopRouteWithChildren,
  R11PathlessLayoutLegalRoute: R11PathlessLayoutLegalRouteWithChildren,
  R11PathlessLayoutShopRoute: R11PathlessLayoutShopRouteWithChildren,
  R13NonNestedProductsRoute: R13NonNestedProductsRouteWithChildren,
  R14LocationCategoryRoute: R14LocationCategoryRoute,
  R16RouteMatchingAboutRoute: R16RouteMatchingAboutRoute,
  R16RouteMatchingProductsRoute: R16RouteMatchingProductsRouteWithChildren,
  R17EscapeCharactersSitemapDotxmlRoute: R17EscapeCharactersSitemapDotxmlRoute,
  R19LoaderProductsRoute: R19LoaderProductsRoute,
  R20PendingComponentProductsRoute: R20PendingComponentProductsRoute,
  R21SearchStringNoReplaceProductsRoute: R21SearchStringNoReplaceProductsRoute,
  R21UseNavigateCheckoutRoute: R21UseNavigateCheckoutRoute,
  R22SearchStringReplaceProductsRoute: R22SearchStringReplaceProductsRoute,
  R23SearchJsonProductsRoute: R23SearchJsonProductsRoute,
  R24SearchJsonZodProductsRoute: R24SearchJsonZodProductsRoute,
  R04ColocationIndexRoute: R04ColocationIndexRoute,
  R05IndexRouteIndexRoute: R05IndexRouteIndexRoute,
  R14LocationIndexRoute: R14LocationIndexRoute,
  R17EscapeCharactersSitemapXmlRoute: R17EscapeCharactersSitemapXmlRoute,
  R18UrlRewritesProductsProductIdRoute: R18UrlRewritesProductsProductIdRoute,
  R21UseNavigateOrdersOrderIdRoute: R21UseNavigateOrdersOrderIdRoute,
  R13NonNestedProductsProductIdCheckoutRoute:
    R13NonNestedProductsProductIdCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
